### ISSUE TITLE
Can't change parameters for use on react native side

### ISSUE THREAD

**Issue by Xeposem** [bndkt/react-native-widget-extension#10]
Hello,

I'm trying to use this module with a few requirements in mind for my project:
- I need to re prebuild the native ios folder every time
- I can't manually change anything in the node_modules folder or the native ios folder

I was trying to change the parameters and such for the update and end activity functions, but I noticed that in the node_modules, the parameters were not correct.
I also noticed that your startActivity will take any arguments and simply pass it to the native side, but your update and end activity function have explicitly stated the parameters.
I tried to manually change the node_modules file but, once I run prebuild again, it overwrites the contents of the node_modules file anyways.

Am I doing something wrong?

**Comment by bndkt** [comment]
Please take a look at this blog post and see if you still have any problems: https://bndkt.com/blog/2023/ios-live-activities. If yes, please open another issue with a reproducible example.
