### ISSUE TITLE
Steps to run example

### ISSUE THREAD

**Issue by brettpthomas** [bndkt/react-native-widget-extension#12]
The app in `example/` doesn't run by default. Seems we need to run a build step first:

```
$ npx expo start
Error: Cannot find module './plugin/build
```

Is it easy to list the steps to run the example?

I'm also happy to send a PR for the readme if you can point me in the right direction.

**Comment by bndkt** [comment]
Working on a blog post and better README right now, will hopefully publish it tomorrow. Yes you need to run the build script in the repo's root directory so that the `/build` and `/plugin/build` directories exist.

**Comment by nathan-ahn** [comment]
README updated to clarify running the example.
