### ISSUE TITLE
Development Workflow

### ISSUE THREAD

**Issue by arnolicious** [bndkt/react-native-widget-extension#17]
I've just gotten started with this amazing library, however I am wondering on best possible development workflow.
Is there a way to update the Widget Swift Code without needing to create a new build after every change?

**Comment by chanphiromsok** [comment]
> I've just gotten started with this amazing library, however I am wondering on best possible development workflow. Is there a way to update the Widget Swift Code without needing to create a new build after every change?

I think you should create the project in SwiftUI because SwiftUI has a preview provider hot update
- for widget development widget in react native Xcode it really heavy for preview provider I recommend to create SwiftUI and build it after you done copy paste to your project
