### ISSUE TITLE
Create more than one widget

### ISSUE THREAD

**Issue by rhuber-rbi** [bndkt/react-native-widget-extension#20]
Hello!! This is just a question as I didn't find the info on the readme or the blog, if I want to create more than one widget how I could make that using your plugin? No rush at all on this, is just a doubt if it's possible or if there is a plan to implement it.

**Comment by nathan-ahn** [comment]
Here's how you can create multiple widgets:
`SampleWidgetExtensionBundle.swift`:
```
import WidgetKit
import SwiftUI

@main
struct SampleWidgetExtensionBundle: WidgetBundle {
    var body: some Widget {
        SampleWidgetExtension()
        SomeOtherSampleWidgetExtension()
    }
}
```
With `SampleWidgetExtension` from the [example](https://github.com/bndkt/react-native-widget-extension/blob/main/example/SampleWidgetExtension/SampleWidgetExtension.swift) and `SomeOtherSampleWidgetExtension` being some other widget implementation.
