### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by Lucaaa03** [bndkt/react-native-widget-extension#22]
When I follow the instructions on how to install this extension, my Expo app compiles, but I can't open it with Expo Go. 
Whenever I do that (with an iPhone 14 Pro Max), I get the following errors:

```
Error: Cannot find native module 'ReactNativeWidgetExtension', js engine: hermes

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

Does anyone know how to fix that or what went wrong?

**Comment by denizutku** [comment]
You cannot use Expo Go with this since it makes modifications to the native code

Check [expo prebuild](https://docs.expo.dev/workflow/prebuild/)

**Comment by Lucaaa03** [comment]
Ah okay, thx for the reply!

Does that mean it can be used when building the app directly on a Mac or is it totally incompatible with the expo framework?

**Comment by denizutku** [comment]
It's like incompatible with Expo Go, not with Expo. If you install a new package with native code changes (or if you add native code) you need to prebuild and run it, you cannot continue using Expo Go.

**Comment by GrinZero** [comment]
I encountered almost all the issues during the process of joining this project, and this project should be marked as unavailable for expo 50+

**Comment by km00776** [comment]
So to even work this in the first place --> we can't use expo go, and from there on wards we need to use a development build?

**Comment by nathan-ahn** [comment]
This package supports Expo 50+ (I'm currently using it for Expo 52). Native code is required so it is impossible to use Expo Go. You'll need to use a [development build](https://docs.expo.dev/develop/development-builds/create-a-build/) for this package to work (as well as any package that requires native code that isn't already included in Expo Go).
