### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by lauridskern** [bndkt/react-native-widget-extension#6]
Could we have a more minimal example, everything I tried to remove from the current example broke it. 
I am not sure what can and cannot be removed. 
I only use it for a simple widget, so no data is passed from rn and it is completely static.

**Comment by loverajoel** [comment]
+1 to this, I couldn't make it work either

**Comment by bndkt** [comment]
@lauridskern @loverajoel I just updates the example and kept it as minimal as possible. Please check it out!
